services:
  - type: web
    name: mueblesribera
    env: docker
    region: oregon
    plan: free
    envVars:
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: muebleriaribera-db
          property: connectionString
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:1MV8g4JS59wJWzwCaqNMHwOoEj+rOAoV9amizaoaWtU=
      - key: APP_URL
        value: https://mueblesribera.onrender.com
      - key: LOG_CHANNEL
        value: stderr

databases:
  - name: muebleriaribera-db
    region: oregon
    plan: free